<?php
$lang= array( 
"dashboard"=>"Dashboard",
"my_profiles"=>"My Profiles",
"manage_profile"=>"Manage Profiles",
"recently_who_viewed"=>"Recently who viewed",
"recently_who_liked"=>"Recently who liked",
"who_viewed_my_contacts"=>"Who Viewed My Contacts",
"recently_who_shortlisted"=>"Recently who Shortlisted",
"matches"=>"Matches",
"browse_matches"=>"Browse Matches",
"basic_search"=>"Basic Search",
"my_contacts"=>"My Contacts",
"my_recently_viewed"=>"My Recently Viewed",
"my_liked"=>"My Liked",
"my_downloaded"=>"My Viewed Contacts",
"short_list_profiles"=>"Short Listed",
"my_invitations"=>"My Invitations",
"support"=>"Support",
"service_requests"=>"Service Requests",
"resolution_center"=>"Resolution Center",
"my_accounts"=>"My Accounts",
"my_orders"=>"My Orders",
"my_invoices"=>"My Invoices",
"my_receipts"=>"My Receipts",
"my_transactions"=>"My Transactions",
"my_wallet"=>"My Wallet",
"mutually_liked_profiles"=>"Mutually liked",
"no_profiles_who_viewed_your_profile"=>"you don't have active profile to view recently who viewed your profile"
);
?>