<?php
    class CodeMaster {
        
        function getData($Request) {
              global $mysql;
              $quries = array("Gender"        => "select * from `_tbl_master_codemaster` Where `HardCode`='SEX'",
                              "ProfileFor"    => "select * from `_tbl_master_codemaster` Where `HardCode`='PROFILESIGNIN'",
                              "MaritalStatus" => "select * from `_tbl_master_codemaster` Where `HardCode`='MARTIALSTATUS'",
                              "Language"      => "select * from `_tbl_master_codemaster` Where `HardCode`='LANGUAGENAMES'",
                              "Religion"      => "select * from `_tbl_master_codemaster` Where `HardCode`='RELINAMES'",
                              "Caste"         => "select * from `_tbl_master_codemaster` Where `HardCode`='CASTNAMES'",
                              "StarName"      => "select * from `_tbl_master_codemaster` Where `HardCode`='STARNAMES'",
                              "Community"     => "select * from `_tbl_master_codemaster` Where `HardCode`='COMMUNITY'",
                              "Nationality"   => "select * from `_tbl_master_codemaster` Where `HardCode`='NATIONALNAMES'",
                              "IncomeRange"   => "select * from `_tbl_master_codemaster` Where `HardCode`='INCOMERANGE'",
                              "Height"        => "select * from `_tbl_master_codemaster` Where `HardCode`='HEIGHTS'",
                              "Diet"          => "select * from `_tbl_master_codemaster` Where `HardCode`='DIETS'",
                              "SmokingHabit"  => "select * from `_tbl_master_codemaster` Where `HardCode`='SMOKINGHABITS'",
                              "Weight"        => "select * from `_tbl_master_codemaster` Where `HardCode`='WEIGHTS'",
                              "BloodGroups"   => "select * from `_tbl_master_codemaster` Where `HardCode`='BLOODGROUPS'",
                              "DocumentType"  => "select * from `_tbl_master_codemaster` Where `HardCode`='DOCTYPES'",
                              "Secure"        => "select * from `_tbl_master_codemaster` Where `HardCode`='SECURE'",
                              "IDProof"       => "select * from `_tbl_master_codemaster` Where `HardCode`='IDPROOF'",
                              "AddressProof"  => "select * from `_tbl_master_codemaster` Where `HardCode`='ADDRESSPROOF'",
                              "DrinkingHabit" => "select * from `_tbl_master_codemaster` Where `HardCode`='DRINKINGHABITS'",
                              "SkinType"      => "select * from `_tbl_master_codemaster` WHERE `HardCode`='COMPLEXIONS'",
                              "BodyType"      => "select * from `_tbl_master_codemaster` Where `HardCode`='BODYTYPES'",
                              "CountryName"   => "select * from `_tbl_master_codemaster` Where `HardCode`='CONTNAMES'",
                              "StateName"     => "select * from `_tbl_master_codemaster` Where `HardCode`='STATNAMES'",
                              "DistrictName"  => "select * from `_tbl_master_codemaster` Where `HardCode`='DISTNAMES'",
                              "AccountType"   => "select * from `_tbl_master_codemaster` Where `HardCode`='ACCOUNTTYPE'",
                              "EmployedAs"    => "select * from `_tbl_master_codemaster` Where `HardCode`='OCCUPATIONS'",
                              "Occupation"    => "select * from `_tbl_master_codemaster` Where `HardCode`='OCCUPATIONTYPES'",
                              "OccupationTypes"          => "select * from `_tbl_master_codemaster` Where `HardCode`='TYPEOFOCCUPATIONS'",
                              "AvailableBankName"        => "select * from `_tbl_master_codemaster` Where `HardCode`='BANKNAMES'",
                              "FamilyType"               => "select * from `_tbl_master_codemaster` Where `HardCode`='FAMILYTYPE'",
                              "FamilyValue"               => "select * from `_tbl_master_codemaster` Where `HardCode`='FAMILYVALUE'",
                              "FamilyAffluence"               => "select * from `_tbl_master_codemaster` Where `HardCode`='FAMILYAFFLUENCE'",
                              "NumberOfBrother"          => "select * from `_tbl_master_codemaster` Where `HardCode`='NUMBEROFBROTHER'",
                              "NumberOfElderBrother"     => "select * from `_tbl_master_codemaster` Where `HardCode`='ELDER'",
                              "NumberOfYoungerBrother"   => "select * from `_tbl_master_codemaster` Where `HardCode`='YOUNGER'",
                              "NumberOfMarriedBrother"   => "select * from `_tbl_master_codemaster` Where `HardCode`='MARRIED'",
                              "NumberOfSisters"          => "select * from `_tbl_master_codemaster` Where `HardCode`='NOOFSISTER'",
                              "NumberOfElderSisters"     => "select * from `_tbl_master_codemaster` Where `HardCode`='ELDERSIS'",
                              "NumberOfYoungerSisters"   => "select * from `_tbl_master_codemaster` Where `HardCode`='YOUNGERSIS'",
                              "NumberOfMarriedSisters"   => "select * from `_tbl_master_codemaster` Where `HardCode`='MARRIEDSIS'",
                              "PhysicallyImpaired"       => "select * from `_tbl_master_codemaster` Where `HardCode`='PHYSICALLYIMPAIRED'",
                              "VisuallyImpaired"         => "select * from `_tbl_master_codemaster` Where `HardCode`='VISUALLYIMPAIRED'",
                              "VisionImpaired"           => "select * from `_tbl_master_codemaster` Where `HardCode`='VISSIONIMPAIRED'",
                              "SpeechImpaired"           => "select * from `_tbl_master_codemaster` Where `HardCode`='SPEECHIMPAIRED'",
                              "RegisterAllowedCountries" => "select *, CONCAT(CodeValue,' (',ParamA,')') as str FROM `_tbl_master_codemaster`  WHERE `HardCode`='CONTNAMES' and ParamB='1'");
              return $mysql->select($quries[$Request]);
        }
    }
?>